// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dictionary} from '../models';

export function ChooseAndOpenDictionary():Promise<string>;

export function CloseDictionary():Promise<void>;

export function CurrentDictionary():Promise<string>;

export function LookupWord(arg1:string):Promise<dictionary.Entry>;

export function LookupWords(arg1:string):Promise<Array<dictionary.Entry>>;

export function OpenDictionary(arg1:string):Promise<void>;

export function SearchCandidates(arg1:string):Promise<Array<string>>;
