// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseAndOpenDictionary() {
  return window['go']['main']['App']['ChooseAndOpenDictionary']();
}

export function CloseDictionary() {
  return window['go']['main']['App']['CloseDictionary']();
}

export function CurrentDictionary() {
  return window['go']['main']['App']['CurrentDictionary']();
}

export function LookupWord(arg1) {
  return window['go']['main']['App']['LookupWord'](arg1);
}

export function LookupWords(arg1) {
  return window['go']['main']['App']['LookupWords'](arg1);
}

export function OpenDictionary(arg1) {
  return window['go']['main']['App']['OpenDictionary'](arg1);
}

export function SearchCandidates(arg1) {
  return window['go']['main']['App']['SearchCandidates'](arg1);
}
