// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dictionary} from '../models';

export function ChooseAndOpenDictionary():Promise<string>;

export function CloseDictionary():Promise<void>;

export function CurrentDictionary():Promise<string>;

export function Library():Promise<Array<main.PackageInfo>>;

export function LookupIn(arg1:string,arg2:string):Promise<dictionary.Entry>;

export function LookupWord(arg1:string):Promise<dictionary.Entry>;

export function OpenDictionary(arg1:string):Promise<void>;

export function RestoreLibrary():Promise<void>;

export function SearchCandidates(arg1:string):Promise<Array<string>>;
